// export enum CompanyCode {
//   "Celogen" = "CG",
//   "CodeGen" = "CGN",
//   "HayCarb" = "HC",
//   "Kelun Life Sciences" = "KL",
//   "Kevilton" = "KV",
//   "Lankem" = "LK",
//   "MAS" = "MAS",
//   "North Sails" = "NS",
//   "Octave" = "OC",
//   "S-Lon" = "SL",
//   "Sands Active" = "SA",
//   "SimCentric" = "SC",
//   "emjay penguin" = "EP",
//   "hcb" = "HCB",
//   "twinery" = "TW",
// }

export enum CompanyCode {
  "KL" = "Kelun Life Sciences (Pvt) Ltd",
  "CG" = "Celogen Lanka (Pvt) Ltd",
  "SA" = "Sands Active (Pvt) Ltd",
  "BRX" = "Brandix Lanka (Pvt) Ltd",
  "MAS" = "MAS Holdings (Pvt) Ltd",
  "CGN" = "CodeGen International (Pvt) Ltd",
  "HCB" = "Hemas Consumer Brands (Pvt) Ltd",
  "OC" = "Octave (Pvt) Ltd",
  "EJ" = "Emjay International (Pvt) Ltd",
  "LK" = "Lankem (Pvt) Ltd",
  "HAY" = "HayCarb PLC",
  "NS" = "North Sails (Pvt) Ltd",
  "SL" = "S-Lon Lanka (Pvt) Ltd",
  "TW" = "MAS Twinery (MAS Innovation (Pvt) Ltd)",
  "MT" = "My Turn Internship Platform - Website Registration",
}
